# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TiKV
tagline:          'TiKV Weekly'
description:      'TiKV is a distributed Key-Value database which is based on the design of Google Spanner and HBase, but it is much simpler without dependency on any distributed file system.'
url:              http://pingcap.github.com/tikv
baseurl:          "/tikv"

author:
  name:           'PingCAP'
  url:            https://www.pingcap.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pingcap/tikv

